/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geneticcracker;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Krzysztof Sedlak
 */
public class GeneticCracker extends javax.swing.JFrame {

    /**
     * Creates new form GeneticCracker
     */
    PopulationGenerator pg;
    SubstitutionCrypter sCrypter;
    TranspositionCrypter tCrypter;
    nGramer nGramerModule;
    KeyGenerator keyGen;
    public GeneticCracker() {
        initComponents();
        
        keyGen= new KeyGenerator(15, "PL");
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel1 = new java.awt.Panel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        transpRadio = new javax.swing.JRadioButton();
        substRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        keyField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        KeySizeField = new javax.swing.JTextField();
        setCode = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        inputFileDirectory = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        chooseInputFileButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextArea();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cryptedArea = new javax.swing.JTextArea();
        cryptButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        decryptCrypt = new javax.swing.JTextArea();
        decryptKeyField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        decryptedArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        trainingPath = new javax.swing.JTextField();
        readTrainingData = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        trainingText = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        ngramResults = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        transpRadio.setLabel("Transpozycja");
        buttonGroup1.add(transpRadio);
        transpRadio.setSelected(true);
        transpRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transpRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(substRadio);
        substRadio.setText("Podstawieniowy");

        jLabel2.setText("Klucz: ");

        keyField.setText("Klucz");

        jButton1.setText("Generuj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Długość:");

        KeySizeField.setText("10");

        setCode.setText("Ustaw");
        setCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keyField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(transpRadio)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KeySizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(substRadio)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(setCode)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transpRadio)
                    .addComponent(jLabel3)
                    .addComponent(KeySizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(substRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(keyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setCode)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Klucze", jPanel2);

        inputFileDirectory.setText("jTextField3");

        jLabel1.setText("Plik:");

        chooseInputFileButton.setLabel("Wybierz");
        chooseInputFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseInputFileButtonActionPerformed(evt);
            }
        });

        inputArea.setColumns(20);
        inputArea.setLineWrap(true);
        inputArea.setRows(5);
        inputArea.setText("ŻYCIE ROZWIJA SIĘ W CZASIE I PRZESTRZENI. CZAS WYZNACZA NIEUCHRONNY CYKL PRZEMIJANIA, OBJAWIAJĄCY SIĘ NARODZINAMI, DOJRZEWANIEM, STARZENIEM SIĘ I ŚMIERCIĄ. CZAS STWARZA I NISZCZY, JAK INDYJSKI BÓG SZIWA, LUCYFER W TRADYCJI JUDEOCHRZEŚCIJAŃSKIEJ, CZY PRAWIE WSZYSTKIE BÓSTWA BUDDYZMU TYBETAŃSKIEGO, POSIADAJĄCE FORMĘ ŁAGODNĄ I GROŹNĄ. JESTEŚMY WOBEC NIEGO BEZSILNI, PONIEWAŻ PRZYNALEŻYMY DO ŚWIATA PRZYRODY, W KTÓRYM COŚ MUSI UMRZEĆ, BY COŚ NOWEGO MOGŁO ZACZĄĆ ŻYĆ. A ZATEM CZAS JEST STRAŻNIKIEM RÓWNOWAGI. WYZNACZA RÓWNE PRAWA DLA WSZYSTKICH GATUNKÓW ROŚLINNYCH I ZWIERZĘCYCH. POŚRÓD NICH TYLKO CZŁOWIEK STARA SIĘ GO PRZECHYTRZYĆ. DOPOMAGA MU W TYM WYOBRAŹNIA. JUŻ OD NIEPAMIĘTNYCH CZASÓW LUDZIE POSZUKIWALI PANACEUM ZAPEWNIAJĄCEGO NIEŚMIERTELNOŚĆ. DLA JEDNYCH CUDOWNĄ RECEPTĄ NA NIEŚMIERTELNOŚĆ BYŁO ŻYCIE WIECZNE. INNI POSZUKIWALI ELIKSIRU ŻYCIA, CUDOWNEGO LEKU, KTÓRY UCZYNI ŚMIERĆ OBOJĘTNĄ. CI POGROMCY CZASU NIE ZDAWALI SOBIE SPRAWY Z TEGO, ŻE WPADLI W PUŁAPKĘ WŁASNEJ NIEMOŻNOŚCI. NIEUSTANNIE ROZMYŚLALI O TYM, JAK UNIKNĄĆ ŚMIERCI, A CZAS IM UPŁYWAŁ I ANI SIĘ NIE OBEJRZELI, A BYŁO PO WSZYSTKIM.");
        inputArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(inputArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputFileDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chooseInputFileButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputFileDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(chooseInputFileButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("Plik");

        jTabbedPane3.addTab("Wejście", jPanel3);

        jTextField3.setText("jTextField3");

        jButton2.setText("Wybierz");

        cryptedArea.setColumns(20);
        cryptedArea.setLineWrap(true);
        cryptedArea.setRows(5);
        jScrollPane2.setViewportView(cryptedArea);

        cryptButton.setText("Szyfruj");
        cryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cryptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cryptButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addGap(0, 59, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cryptButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Wyjście", jPanel4);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane2)
                    .addComponent(jTabbedPane4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane4))
            .addComponent(jTabbedPane3)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Klucz");

        jTabbedPane1.addTab("Szyfrowanie", panel1);

        decryptCrypt.setColumns(20);
        decryptCrypt.setLineWrap(true);
        decryptCrypt.setRows(5);
        jScrollPane3.setViewportView(decryptCrypt);

        decryptKeyField.setText("Klucz");
        decryptKeyField.setToolTipText("");

        jButton3.setText("Deszyfruj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        decryptedArea.setColumns(20);
        decryptedArea.setLineWrap(true);
        decryptedArea.setRows(5);
        jScrollPane4.setViewportView(decryptedArea);

        jLabel4.setText("Zaszyfrowany");

        jLabel5.setText("Odszyfrowany");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addComponent(decryptKeyField))
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton3)))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(227, 227, 227))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(decryptKeyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        jTabbedPane1.addTab("Deszyfracja Kodem", jPanel1);

        jButton5.setText("Inicjuj p");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton5)
                .addContainerGap(829, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Łamanie kodu", jPanel5);

        trainingPath.setText("Plik treningowy");

        readTrainingData.setText("Wczytaj");
        readTrainingData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readTrainingDataActionPerformed(evt);
            }
        });

        trainingText.setColumns(20);
        trainingText.setLineWrap(true);
        trainingText.setRows(5);
        jScrollPane5.setViewportView(trainingText);

        ngramResults.setColumns(20);
        ngramResults.setLineWrap(true);
        ngramResults.setRows(5);
        jScrollPane6.setViewportView(ngramResults);

        jLabel6.setText("Ustawienie n:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5" }));
        jComboBox1.setSelectedIndex(1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton4.setText("Ucz sie");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(trainingPath, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(readTrainingData)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane6)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(92, 92, 92))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainingPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(readTrainingData)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trening(ngram)", jPanel6);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"_W_", null},
                {"_A_", null},
                {"NAD", null},
                {"IE_", null},
                {"NIE", null},
                {"PRZ", null},
                {"_Z_", null},
                {"JAK", null},
                {"JUŻ", null},
                {"WSZ", null},
                {"_NA", null},
                {"_PR", null},
                {"_ZA", null},
                {"_PO", null},
                {"EGO", null},
                {"WIE", null},
                {"RZE", null},
                {"GFD", null},
                {"PRT", null},
                {"ZST", null},
                {"DWR", null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "nGram", "Punkty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jScrollPane7.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tabela punktowania");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel7)))
                .addContainerGap(727, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Własna funckja oceny", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 923, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Parametry łamacza", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
////////
//////// GENERATE KEY METHOD 
        
      //  keyGen.printAlphabets();
        
        int keyS = Integer.parseInt(KeySizeField.getText());
    
        String cipherKey="";
        if(substRadio.isSelected()){
          char[] code =  keyGen.getRandomFromChar(keyGen.AlphabetForSubstitution);
            for(char z : code){
                cipherKey=cipherKey+z;
            }
        }
        else{
            int[] code =  keyGen.getRandomFromInt(keyGen.AlphabetForTransposition, keyS);
             for(int z : code){
                cipherKey=cipherKey+z+",";
            }
        }
       keyField.setText(cipherKey);
        
            
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void transpRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transpRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transpRadioActionPerformed

    private void cryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cryptButtonActionPerformed
     // sCrypter = new SubstitutionCrypter(keyGen.AlphabetForSubstitution, keyGen.codeSubs);
      
    // cryptedArea.setText(sCrypter.cryptString(inputArea.getText()));
        
        if(substRadio.isSelected()){
             sCrypter = new SubstitutionCrypter(keyGen.AlphabetForSubstitution, keyGen.codeSubs);      
              cryptedArea.setText(sCrypter.cryptString(inputArea.getText()));
        }
        else{
        tCrypter = new TranspositionCrypter(keyGen.codeTrans);
        tCrypter.initMatrix(inputArea.getText());
        tCrypter.printTextMatrixWithCode(tCrypter.matrix);
        tCrypter.cryptMatrix(tCrypter.matrix, tCrypter.keyTable);
        cryptedArea.setText(tCrypter.matrixToString(tCrypter.crypted));
        }
    }//GEN-LAST:event_cryptButtonActionPerformed

    private void setCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCodeActionPerformed
String code = keyField.getText();
     if(code.contains(",")){// przecinkowy
      String[] numbersTable= code.split(",");
      keyGen.codeTrans= new int[numbersTable.length];
      for(int i=0; i<numbersTable.length;i++){
          keyGen.codeTrans[i]=Integer.parseInt(numbersTable[i]);
      }
      
     }
     else{//alfabet
     keyGen.codeSubs= new char[code.length()];
     for(int i= 0; i<code.length();i++){
         keyGen.codeSubs[i]=code.charAt(i);
     }
         
     }
        

// TODO add your handling code here:
    }//GEN-LAST:event_setCodeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  String code = decryptKeyField.getText();
        if(code.contains(",")){////tranzycyjny
            
             String[] numbersTable= code.split(",");
     int[] key= new int[numbersTable.length];
      for(int i=0; i<numbersTable.length;i++){
          key[i]=Integer.parseInt(numbersTable[i]);
      }
      
            
               tCrypter = new TranspositionCrypter(key);
        tCrypter.initMatrix(decryptCrypt.getText());
        tCrypter.printTextMatrixWithCode(tCrypter.matrix);
        tCrypter.decryptMatrix(tCrypter.matrix, tCrypter.keyTable);
     decryptedArea.setText(tCrypter.matrixToString(tCrypter.crypted));
            
            
        }
        else{///alfabetyczne podstawienie
            //ustaw kod
           char[] codeForDec = new char[code.length()];
     for(int i= 0; i<codeForDec.length;i++){
       codeForDec[i]=code.charAt(i);
     }
             sCrypter = new SubstitutionCrypter(codeForDec,keyGen.AlphabetForSubstitution);  
             
            decryptedArea.setText(sCrypter.cryptString(decryptCrypt.getText()));
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int n = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        nGramerModule=new nGramer(n);
        nGramerModule.readText(trainingText.getText());
        nGramerModule.count();
        nGramerModule.printHash(ngramResults);




// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void readTrainingDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readTrainingDataActionPerformed
 JFileChooser fileChooser = new JFileChooser();
  File selectedFile = null;
 FileFilter filter = new FileNameExtensionFilter("Tekst", new String[] {"txt"});
 fileChooser.setFileFilter(filter);
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
         selectedFile = fileChooser.getSelectedFile();
          trainingPath.setText(selectedFile.getAbsolutePath());
        }
         
        String readedFile = null;
    BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(selectedFile));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GeneticCracker.class.getName()).log(Level.SEVERE, null, ex);
        }
    try {
        StringBuilder sb = new StringBuilder();
        String line = br.readLine();

        while (line != null) {
            sb.append(line);
            sb.append(System.lineSeparator());
            line = br.readLine();
        }
      readedFile= sb.toString();
    }   catch (IOException ex) {
            Logger.getLogger(GeneticCracker.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
     try {
         br.close();
     } catch (IOException ex) {
         Logger.getLogger(GeneticCracker.class.getName()).log(Level.SEVERE, null, ex);
     }
    }
    
    trainingText.setText(readedFile);
    
    }//GEN-LAST:event_readTrainingDataActionPerformed

    
    private void chooseInputFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseInputFileButtonActionPerformed
 JFileChooser fileChooser = new JFileChooser();
 FileFilter filter = new FileNameExtensionFilter("Tekst", new String[] {"txt"});
 fileChooser.setFileFilter(filter);
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
          File selectedFile = fileChooser.getSelectedFile();
          inputFileDirectory.setText(selectedFile.getAbsolutePath());
        }  
// TODO add your handling code here:
    }//GEN-LAST:event_chooseInputFileButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
        pg=new PopulationGenerator(10, 1, 100);
      //  pg.printTransPop();
        pg.printSubsPop();
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneticCracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneticCracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneticCracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneticCracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneticCracker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KeySizeField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton chooseInputFileButton;
    private javax.swing.JButton cryptButton;
    private javax.swing.JTextArea cryptedArea;
    private javax.swing.JTextArea decryptCrypt;
    private javax.swing.JTextField decryptKeyField;
    private javax.swing.JTextArea decryptedArea;
    private javax.swing.JTextArea inputArea;
    private javax.swing.JTextField inputFileDirectory;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField keyField;
    private javax.swing.JTextArea ngramResults;
    private java.awt.Panel panel1;
    private javax.swing.JButton readTrainingData;
    private javax.swing.JButton setCode;
    private javax.swing.JRadioButton substRadio;
    private javax.swing.JTextField trainingPath;
    private javax.swing.JTextArea trainingText;
    private javax.swing.JRadioButton transpRadio;
    // End of variables declaration//GEN-END:variables
}
